#!/bin/sh

notifyAudioMute() {
    # msg=$1
    notify-send -h string:x-dunst-stack-tag:volume System "Volume muted"
    # dunstify -h string:x-dunst-stack-tag:volume -h int:value:0 "System" "Volume $msg"
}

notifyMPRIS() {
    title="$1"
    artist="$2"
    notify-send -h string:x-dunst-stack-tag:player "$title" "$artist"
}

notifyAudio() {
    in=$1
    mute=$2
    if [ $mute = "[MUTED]" ]; then
        notifyAudioMute "muted"
    else
        notify-send -h string:x-dunst-stack-tag:volume -h int:value:"$in" System "Volume: $in%"
    fi
    # exec pkill -RTMIN+1 bar
}

notifyBacklight() {
    in=$1
    notify-send -h string:x-dunst-stack-tag:backlight -h int:value:"$in" System Brightness
    # dunstify -h string:x-dunst-stack-tag:backlight -h int:value:"$in" "System" "Brightness"
    exec pkill -RTMIN+2 bar
}

notifyReminders() {
    in=$1
    remind -k"dunstify -h string:x-dunst-tag:reminders Reminders %s" remind.rem
}

t=$1
in=$(cat /dev/stdin)

case "$t" in
    audio) 
        set -- $in
        v=$1
        mute=$2
        notifyAudio $v $mute
        ;;
    backlight)
        notifyBacklight "$in"
        ;;
    mpris)
        set -- "$in"
        title="$(echo $in | cut -d ',' -f1)"
        artist="$(echo $in | cut -d ',' -f2)"
        notifyMPRIS "$title" "$artist"
        ;;
    rem)
        notifyReminders "$in"
        ;;
    default)
        ;;
esac
