{ ... }:
{
  imports = [
    ./alacritty.nix
    ./fzf.nix
    ./git.nix
    ./mpv.nix
    ./xdg.nix
    ./bash.nix
    ./mako.nix
    ./tmux.nix
    ./beets.nix
    ./fonts.nix
    ./river.nix
    ./fuzzel.nix
    ./nixvim.nix
    ./waybar.nix
    ./firefox.nix
    ./wallust.nix
    ./wayland.nix
    ./zathura.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./hyprcursor.nix
    ./swaylock.nix
    ./dircolors.nix
    ./nixneovim.nix
  ];
}
